#pragma once

#include <iostream>
#include <vector>
#include <cmath>

#include <gtest/gtest.h>
#include "Eigen/Core"
#include "BuildPolyhedra.hpp"
#include "Polyhedra.hpp"
#include "Utils.hpp"

using namespace PolyhedraLibrary;
using namespace std;
using namespace Eigen;

TEST(TestUtils, TestFindBarycenter)
{
    
}

TEST(TestUtils, TestOntoTheUnitSphereTetrahedron)
{
    /* The test will check whether the coordinates of the points belonging to the unit sphere
    generated by our code are "equal as doubles" to the ones found thanks to the function */

    /* Let's create the polyhedron */
    BuildPolyhedra constructor(3, 3);
    constructor.DataPolyhedra();
    GEOPolyhedron polyhedron = constructor.GetPolyhedron();

    /* Let's copy the coordinates of its vertices that we worte in the code as points 
    belonging to the unit sphere */
    Eigen::MatrixXd oldCoordVertices = polyhedron.CoordVertices;

    /* Let's use the function we're testing to update the coordinates of the vertices: 
    this action will not affect the copy "oldCoordVertices" */
    OntoTheUnitSphere(polyhedron);
    /* Let's rename it for code readability */
    Eigen::MatrixXd& newCoordVertices = polyhedron.CoordVertices;

    
    for(int vertex = 0; vertex < polyhedron.NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            EXPECT_DOUBLE_EQ(newCoordVertices(coordinate, vertex), oldCoordVertices(coordinate, vertex));
        }
    }
}

TEST(TestUtils, TestOntoTheUnitSphereOctahedron)
{    
    BuildPolyhedra constructor(3, 4);
    constructor.DataPolyhedra();
    GEOPolyhedron polyhedron = constructor.GetPolyhedron();

    Eigen::MatrixXd oldCoordVertices = polyhedron.CoordVertices;
    OntoTheUnitSphere(polyhedron);
    Eigen::MatrixXd& newCoordVertices = polyhedron.CoordVertices;

    for(int vertex = 0; vertex < polyhedron.NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            EXPECT_DOUBLE_EQ(newCoordVertices(coordinate, vertex), oldCoordVertices(coordinate, vertex));
        }
    }
}

TEST(TestUtils, TestOntoTheUnitSphereIcosahedron)
{
    BuildPolyhedra constructor(3, 5);
    constructor.DataPolyhedra();
    GEOPolyhedron polyhedron = constructor.GetPolyhedron();

    Eigen::MatrixXd oldCoordVertices = polyhedron.CoordVertices;
    OntoTheUnitSphere(polyhedron);
    Eigen::MatrixXd& newCoordVertices = polyhedron.CoordVertices;

    for(int vertex = 0; vertex < polyhedron.NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            EXPECT_DOUBLE_EQ(newCoordVertices(coordinate, vertex), oldCoordVertices(coordinate, vertex));
        }
    }
}

TEST(TestUtils, TestOntoTheUnitSphereMoreGeneral)
{
    /* Let's create a polyhedron with a "CoordVertices" matrix composed by columns filled 
    with the same integer */

    GEOPolyhedron testPolyhedron;

    /* Let's define arbitrarily a number of vertices for the polyhedron */
    testPolyhedron.NumVertices = 10;
    int& NumVertices = testPolyhedron.NumVertices;

    Eigen::MatrixXd& CoordVertices = testPolyhedron.CoordVertices;
    CoordVertices.resize(3, NumVertices);

    for(int vertex = 0; vertex < NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            CoordVertices(coordinate, vertex) = vertex + 1;
        }
    }

    Eigen::MatrixXd oldCoordVertices = CoordVertices;
    /* Let's normalize each column of the copied matrix using pen and paper: we need to divide each element 
    of the column by the value "element * sqrt(3)" because of how we defined "CoordVertices" */
    for(int vertex = 0; vertex < NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            oldCoordVertices(coordinate, vertex) /= ((vertex + 1) * sqrt(3));
        }
    }
    
    /* Let's use the function we're testing */
    OntoTheUnitSphere(testPolyhedron);
    Eigen::MatrixXd& newCoordVertices = CoordVertices;

    for(int vertex = 0; vertex < NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            EXPECT_DOUBLE_EQ(newCoordVertices(coordinate, vertex), oldCoordVertices(coordinate, vertex));
        }
    }
}


TEST(TestUtils, TestBFS)
{
    vector<vector<int>> adjList = { {1, 2},     // Nodo 0 
                                    {2},        // Nodo 1 
                                    {0, 3, 4},  // Nodo 2 
                                    {4},        // Nodo 3
                                    {3, 5},     // Nodo 4
                                    {4, 3} };   // Nodo 5  
    int v1 = 2;
    int v2 = 5;
    int numVert = 6;
    double lengthEdge = 1.0;
    double lengthPath = 0.0;
    vector<int> minPathBFS = BFS(adjList, v1, v2, numVert, lengthEdge, lengthPath);
    vector<int> minPathEx = {2, 4, 5};
    EXPECT_EQ(minPathBFS, minPathEx);
}

TEST(TestUtils, TestDijkstra)
{
    vector<vector<int>> adjList = { {1, 2, 3, 4},   // Nodo 0 
                                    {0},            // Nodo 1 
                                    {1, 3, 4},      // Nodo 2 
                                    {2, 4},         // Nodo 3
                                    {0, 1} };       // Nodo 4
    MatrixXd matrWeights(5, 5); 
    matrWeights << 0, 5, 2, 3, 4,
                   5, 0, 0, 0, 0,
                   0, 2, 0, 2, 1,
                   0, 0, 1, 0, 2,
                   4, 1, 0, 0, 0; 
    int v1 = 3;
    int v2 = 0;
    int numVert = 5;
    double lengthPath = 0.0;
    vector<int> minPathDijkstra = Dijkstra(adjList, v1, v2, numVert, matrWeights, lengthPath);
    vector<int> minPathEx = {3, 4, 0};
    EXPECT_EQ(minPathDijkstra, minPathEx);
    EXPECT_DOUBLE_EQ(lengthPath, 6.0);

    vector<vector<int>> adjList1 = { {1, 2},        // Nodo 0 
                                    {0, 2, 3, 4},   // Nodo 1 
                                    {0, 1, 4},      // Nodo 2 
                                    {1, 4},         // Nodo 3
                                    {1, 2, 3} };    // Nodo 4
    MatrixXd matrWeights1(5, 5); 
    matrWeights1 << 0, 10, 1, 0, 0,
                   10, 0, 2, 9, 5,
                   1, 2, 0, 0, 20,
                   0, 9, 0, 0, 3,
                   0, 5, 20, 3, 0; 
    int v1_1 = 3;
    int v2_1 = 2;
    int numVert1 = 5;
    double lengthPath1 = 0.0;
    vector<int> minPathDijkstra1 = Dijkstra(adjList1, v1_1, v2_1, numVert1, matrWeights1, lengthPath1);
    vector<int> minPathEx1 = {3, 4, 1, 2};
    EXPECT_EQ(minPathDijkstra1, minPathEx1);
    EXPECT_DOUBLE_EQ(lengthPath1, 10.0);
}

TEST(TestUtils, TestDistanceSquaredBetween)
{
    /* Let's intialise and define a mtrix of coordintes decided by us. The distance between 
    each couple of vertices (composed by a vertex and the next one) is known by us, because we calculated
    it with pen and paper */
    Eigen::Matrix<double, 3, 8> m;
    m << 61.0/2.0, 11.0/2.0, 32.0/3.0, 5.0/3.0, 9.0/2.0, 1.0/2.0, 4*sqrt(3)/3.0, 2*sqrt(3)/3.0,
         0, 0, 11.0/2.0, 35.0/2.0, 1.0/3.0, 10.0/3.0, 7*sqrt(3)/6.0, 11*sqrt(3)/6.0,
         0, 0, 0, 0, 0, 0, 13*sqrt(3)/9.0, 7*sqrt(3)/9.0;

    /* Let's create a GEOPolyhedron; the matrix defined above will become the "CoordVertices"
    matrix of the structure */
    GEOPolyhedron testPolyhedron;
    testPolyhedron.CoordVertices = m;
    
    /* Let's define two variables which will be used as arguments for the function we're testing:
    "DistanceSquaredBetween" */
    int vertex1 = 0;
    int vertex2 = 1;
    EXPECT_DOUBLE_EQ(625, DistanceSquaredBetween(testPolyhedron, vertex1, vertex2));

    vertex1 = 2;
    vertex2 = 3;
    EXPECT_DOUBLE_EQ(225, DistanceSquaredBetween(testPolyhedron, vertex1, vertex2));

    vertex1 = 4;
    vertex2 = 5;
    EXPECT_DOUBLE_EQ(25, DistanceSquaredBetween(testPolyhedron, vertex1, vertex2));

    vertex1 = 6;
    vertex2 = 7;
    EXPECT_DOUBLE_EQ(4, DistanceSquaredBetween(testPolyhedron, vertex1, vertex2));
}