#pragma once

#include <iostream>
#include <vector>

#include <gtest/gtest.h>
#include "Eigen/Core"
#include "Sources.hpp"

using namespace PolyhedraLibrary;
using namespace std;
using namespace Eigen;

TEST(TestUtils, TestFindBarycenter)
{
    // Let's create the tetrahedron
    GEOPolyhedron tetrahedron;
    tetrahedron.p = 3;
    tetrahedron.q = 3;
    tetrahedron.CreateStartingPolyhedron();

    // Choose a face of the tetrahedron (given by the indices of its 3 vertices)
    Eigen::Vector3i vertFace = {0, 2, 3};

    // Get the coordinates of each vertex of the face
    Eigen::Vector3d v1 = tetrahedron.CoordVertices.col(vertFace(0));
    Eigen::Vector3d v2 = tetrahedron.CoordVertices.col(vertFace(1));
    Eigen::Vector3d v3 = tetrahedron.CoordVertices.col(vertFace(2));

    // Compute the expected barycenter through the average of the three vertices
    Eigen::Vector3d barycenterTetraEx = Eigen::Vector3d::Zero();
    barycenterTetraEx(0) = (v1(0) + v2(0) + v3(0))/3.0;
    barycenterTetraEx(1) = (v1(1) + v2(1) + v3(1))/3.0;
    barycenterTetraEx(2) = (v1(2) + v2(2) + v3(2))/3.0;

    // Compute the barycenter using the function to be tested
    Eigen::Vector3d barycenterTetraToCheck = FindBarycenter(tetrahedron, vertFace);

    // Let's create the octahedron
    GEOPolyhedron octahedron;
    octahedron.p = 3;
    octahedron.q = 4;
    octahedron.CreateStartingPolyhedron();

    // Choose a face of the octahedron (given by the indices of its 3 vertices)
    vertFace = {0, 3, 5};

    // Get the coordinates of each vertex of the face
    v1 = octahedron.CoordVertices.col(vertFace(0));
    v2 = octahedron.CoordVertices.col(vertFace(1));
    v3 = octahedron.CoordVertices.col(vertFace(2));

    // Compute the expected barycenter through the average of the three vertices
    Eigen::Vector3d barycenterOctaEx = Eigen::Vector3d::Zero();
    barycenterOctaEx(0) = (v1(0) + v2(0) + v3(0))/3.0;
    barycenterOctaEx(1) = (v1(1) + v2(1) + v3(1))/3.0;
    barycenterOctaEx(2) = (v1(2) + v2(2) + v3(2))/3.0;

    // Compute the barycenter using the function to be tested
    Eigen::Vector3d barycenterOctaToCheck = FindBarycenter(octahedron, vertFace);

    // Let's create the icosahedron
    GEOPolyhedron icosahedron;
    icosahedron.p = 3;
    icosahedron.q = 5;
    icosahedron.CreateStartingPolyhedron();

    // Choose a face of the icosahedron (given by the indices of its 3 vertices)
    vertFace = {0, 8, 11};

    // Get the coordinates of each vertex of the face
    v1 = icosahedron.CoordVertices.col(vertFace(0));
    v2 = icosahedron.CoordVertices.col(vertFace(1));
    v3 = icosahedron.CoordVertices.col(vertFace(2));

    // Compute the expected barycenter through the average of the three vertices
    Eigen::Vector3d barycenterIcosaEx = Eigen::Vector3d::Zero();
    barycenterIcosaEx(0) = (v1(0) + v2(0) + v3(0))/3.0;
    barycenterIcosaEx(1) = (v1(1) + v2(1) + v3(1))/3.0;
    barycenterIcosaEx(2) = (v1(2) + v2(2) + v3(2))/3.0;

    // Compute the barycenter using the function to be tested
    Eigen::Vector3d barycenterIcosaToCheck = FindBarycenter(icosahedron, vertFace);

    // Compare the computed barycenters' coordinates with the expected values
    EXPECT_DOUBLE_EQ(barycenterTetraToCheck(0), barycenterTetraEx(0));
    EXPECT_DOUBLE_EQ(barycenterTetraToCheck(1), barycenterTetraEx(1));
    EXPECT_DOUBLE_EQ(barycenterTetraToCheck(2), barycenterTetraEx(2));

    EXPECT_DOUBLE_EQ(barycenterOctaToCheck(0), barycenterOctaEx(0));
    EXPECT_DOUBLE_EQ(barycenterOctaToCheck(1), barycenterOctaEx(1));
    EXPECT_DOUBLE_EQ(barycenterOctaToCheck(2), barycenterOctaEx(2));

    EXPECT_DOUBLE_EQ(barycenterIcosaToCheck(0), barycenterIcosaEx(0));
    EXPECT_DOUBLE_EQ(barycenterIcosaToCheck(1), barycenterIcosaEx(1));
    EXPECT_DOUBLE_EQ(barycenterIcosaToCheck(2), barycenterIcosaEx(2));
}

TEST(TestUtils, TestOntoTheUnitSphereTetrahedron)
{
    /* The test will check whether the coordinates of the points belonging to the unit sphere
    generated by our code are "equal as doubles" to the ones found thanks to the function */

    /* Let's create the polyhedron */
    GEOPolyhedron polyhedron;
    polyhedron.p = 3;
    polyhedron.q = 3;
    polyhedron.CreateStartingPolyhedron();

    /* Let's copy the coordinates of its vertices that we worte in the code as points 
    belonging to the unit sphere */
    Eigen::MatrixXd oldCoordVertices = polyhedron.CoordVertices;

    /* Let's use the function we're testing to update the coordinates of the vertices: 
    this action will not affect the copy "oldCoordVertices" */
    OntoTheUnitSphere(polyhedron);
    /* Let's rename it for code readability */
    Eigen::MatrixXd& newCoordVertices = polyhedron.CoordVertices;

    
    for(int vertex = 0; vertex < polyhedron.NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            EXPECT_DOUBLE_EQ(newCoordVertices(coordinate, vertex), oldCoordVertices(coordinate, vertex));
        }
    }
}

TEST(TestUtils, TestOntoTheUnitSphereOctahedron)
{    
    GEOPolyhedron polyhedron;
    polyhedron.p = 3;
    polyhedron.q = 4;
    polyhedron.CreateStartingPolyhedron();

    Eigen::MatrixXd oldCoordVertices = polyhedron.CoordVertices;
    OntoTheUnitSphere(polyhedron);
    Eigen::MatrixXd& newCoordVertices = polyhedron.CoordVertices;

    for(int vertex = 0; vertex < polyhedron.NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            EXPECT_DOUBLE_EQ(newCoordVertices(coordinate, vertex), oldCoordVertices(coordinate, vertex));
        }
    }
}

TEST(TestUtils, TestOntoTheUnitSphereIcosahedron)
{
    GEOPolyhedron polyhedron;
    polyhedron.p = 3;
    polyhedron.q = 5;
    polyhedron.CreateStartingPolyhedron();

    Eigen::MatrixXd oldCoordVertices = polyhedron.CoordVertices;
    OntoTheUnitSphere(polyhedron);
    Eigen::MatrixXd& newCoordVertices = polyhedron.CoordVertices;

    for(int vertex = 0; vertex < polyhedron.NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            EXPECT_DOUBLE_EQ(newCoordVertices(coordinate, vertex), oldCoordVertices(coordinate, vertex));
        }
    }
}

TEST(TestUtils, TestOntoTheUnitSphereMoreGeneral)
{
    /* Let's create a polyhedron with a "CoordVertices" matrix composed by columns filled 
    with the same integer */

    GEOPolyhedron testPolyhedron;

    /* Let's define arbitrarily a number of vertices for the polyhedron */
    testPolyhedron.NumVertices = 10;
    int& NumVertices = testPolyhedron.NumVertices;

    Eigen::MatrixXd& CoordVertices = testPolyhedron.CoordVertices;
    CoordVertices.resize(3, NumVertices);

    for(int vertex = 0; vertex < NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            CoordVertices(coordinate, vertex) = vertex + 1;
        }
    }

    Eigen::MatrixXd oldCoordVertices = CoordVertices;
    /* Let's normalize each column of the copied matrix using pen and paper: we need to divide each element 
    of the column by the value "element * sqrt(3)" because of how we defined "CoordVertices" */
    for(int vertex = 0; vertex < NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            oldCoordVertices(coordinate, vertex) /= ((vertex + 1) * sqrt(3));
        }
    }
    
    /* Let's use the function we're testing */
    OntoTheUnitSphere(testPolyhedron);
    Eigen::MatrixXd& newCoordVertices = CoordVertices;

    for(int vertex = 0; vertex < NumVertices; vertex++){
        for(int coordinate = 0; coordinate < 3; coordinate++){
            EXPECT_DOUBLE_EQ(newCoordVertices(coordinate, vertex), oldCoordVertices(coordinate, vertex));
        }
    }
}

TEST(TestUtils, TestBFS)
{
    vector<vector<int>> adjList = { {1, 2},     // vertex 0 
                                    {2},        // vertex 1 
                                    {0, 3, 4},  // vertex 2 
                                    {4},        // vertex 3
                                    {3, 5},     // vertex 4
                                    {4, 3} };   // vertex 5  
    int v1 = 2;
    int v2 = 5;
    GEOPolyhedron polyhedron;
    polyhedron.NumVertices = 6;
    polyhedron.CoordVertices.resize(3, 6); 
    polyhedron.CoordVertices <<0, 0, 0, 0, 1, -1,
                                0, 0, 1, -1, 0, 0,
                                1, -1, 0, 0, 0, 0;
    double lengthPath = 0.0;
    vector<int> minPathBFS = BFS(adjList, polyhedron, v1, v2, lengthPath);
    vector<int> minPathEx = {2, 4, 5};
    EXPECT_EQ(minPathBFS, minPathEx);
}

TEST(TestUtils, TestDijkstra)
{
    vector<vector<int>> adjList = { {1, 2, 3, 4},   // vertex 0 
                                    {0},            // vertex 1 
                                    {1, 3, 4},      // vertex 2 
                                    {2, 4},         // vertex 3
                                    {0, 1} };       // vertex 4
    MatrixXd matrWeights(5, 5); 
    matrWeights << 0, 5, 2, 3, 4,
                   5, 0, 0, 0, 0,
                   0, 2, 0, 2, 1,
                   0, 0, 1, 0, 2,
                   4, 1, 0, 0, 0; 
    int v1 = 3;
    int v2 = 0;
    GEOPolyhedron polyhedron;
    polyhedron.NumVertices = 5;
    double lengthPath = 0.0;
    vector<int> minPathDijkstra = Dijkstra(adjList, polyhedron, v1, v2, matrWeights, lengthPath);
    vector<int> minPathEx = {3, 4, 0};
    EXPECT_EQ(minPathDijkstra, minPathEx);
    EXPECT_DOUBLE_EQ(lengthPath, 6.0);

    vector<vector<int>> adjList1 = { {1, 2},        // vertex 0 
                                    {0, 2, 3, 4},   // vertex 1 
                                    {0, 1, 4},      // vertex 2 
                                    {1, 4},         // vertex 3
                                    {1, 2, 3} };    // vertex 4
    MatrixXd matrWeights1(5, 5); 
    matrWeights1 << 0, 10, 1, 0, 0,
                   10, 0, 2, 9, 5,
                   1, 2, 0, 0, 20,
                   0, 9, 0, 0, 3,
                   0, 5, 20, 3, 0; 
    int v1_1 = 3;
    int v2_1 = 2;
    // int numVert1 = 5;
    double lengthPath1 = 0.0;
    vector<int> minPathDijkstra1 = Dijkstra(adjList1, polyhedron, v1_1, v2_1, matrWeights1, lengthPath1);
    vector<int> minPathEx1 = {3, 4, 1, 2};
    EXPECT_EQ(minPathDijkstra1, minPathEx1);
    EXPECT_DOUBLE_EQ(lengthPath1, 10.0);
}

TEST(TestUtils, TestDistanceSquaredBetween)
{
    /* Let's intialise and define a mtrix of coordintes decided by us. The distance between 
    each couple of vertices (composed by a vertex and the next one) is known by us, because we calculated
    it with pen and paper */
    Eigen::Matrix<double, 3, 8> m;
    m << 61.0/2.0, 11.0/2.0, 32.0/3.0, 5.0/3.0, 9.0/2.0, 1.0/2.0, 4*sqrt(3)/3.0, 2*sqrt(3)/3.0,
         0, 0, 11.0/2.0, 35.0/2.0, 1.0/3.0, 10.0/3.0, 7*sqrt(3)/6.0, 11*sqrt(3)/6.0,
         0, 0, 0, 0, 0, 0, 13*sqrt(3)/9.0, 7*sqrt(3)/9.0;

    /* Let's create a GEOPolyhedron; the matrix defined above will become the "CoordVertices"
    matrix of the structure */
    GEOPolyhedron testPolyhedron;
    testPolyhedron.CoordVertices = m;
    
    /* Let's define two variables which will be used as arguments for the function we're testing:
    "DistanceSquaredBetween" */
    int vertex1 = 0;
    int vertex2 = 1;
    EXPECT_DOUBLE_EQ(625, testPolyhedron.DistanceSquaredBetween(vertex1, vertex2));

    vertex1 = 2;
    vertex2 = 3;
    EXPECT_DOUBLE_EQ(225, testPolyhedron.DistanceSquaredBetween(vertex1, vertex2));

    vertex1 = 4;
    vertex2 = 5;
    EXPECT_DOUBLE_EQ(25, testPolyhedron.DistanceSquaredBetween(vertex1, vertex2));

    vertex1 = 6;
    vertex2 = 7;
    EXPECT_DOUBLE_EQ(4, testPolyhedron.DistanceSquaredBetween(vertex1, vertex2));
}